version: '3.7'

services:
  default:
    image: adrianrudnik/maintenance-server
    restart: always
    ports:
      - 8181:80
    environment:
        SERVER_PORT: :80
    volumes:
      - ./pages/default.html:/app/index.html
  swissgamingclan:
    image: adrianrudnik/maintenance-server
    restart: always
    ports:
      - 8282:80
    environment:
        SERVER_PORT: :80
    volumes:
      - ./pages/swissgamingclan.html:/app/index.html